### ISSUE TITLE
can't use calc in less

### ISSUE THREAD

**Issue by eldyvoon** [webpack-contrib/less-loader#149]
This height: calc(100vh - 50px);

became this 

height: 50px;

after I used less-loader

**Comment by rizedr** [comment]
@eldyvoon In less you need to [escape your string](https://github.com/SomMeri/less4j/wiki/Less-Language-Escaping), this meaning your write it as:
```
height: ~"calc(100vh - 50px)";
```

**Comment by shatle** [comment]
#107

**Comment by originlondon-dev-transfer** [comment]
Again, #107 is not a proper solution and this issue should not be closed IMHO: my comment there is:

Thank you to dyf19118 for posting a work around. But I don't see why the issue has been closed.

That isn't a permanent solution, really. It is just work around.

This needs to work- calc() is fairly central to css.

The LESS documentation says that you should use @import (inline) because;

"although Less supports most known standards CSS, it does not support comments in some places and does not support all known CSS hacks without modifying the CSS."

calc() is not an obscure hack.

**Comment by wufeng87** [comment]
https://github.com/ant-design/ant-design/issues/28939
Upgrade to less@^3.1.0 can solve this problem for me.
