### ISSUE TITLE
webpack less-loader can keep comments?

### ISSUE THREAD

**Issue by Sapphire2k** [webpack-contrib/less-loader#157]
Comments are useful in css while using postcss plugins, eg: postcss-px2rem

which transforms

```
.selector {
    width: 150px;
    height: 64px; /*px*/
    font-size: 28px; /*px*/
    border: 1px solid #ddd; /*no*/
}
```
to

```
.selector {
    width: 2rem;
    border: 1px solid #ddd;
}
[data-dpr="1"] .selector {
    height: 32px;
    font-size: 14px;
}
[data-dpr="2"] .selector {
    height: 64px;
    font-size: 28px;
}
[data-dpr="3"] .selector {
    height: 96px;
    font-size: 42px;
}
```
But less-loader delete comments first, so postcss-px2rem could not generate the right result
By the way, sass-loader is allowed when add the param `outputStyle=expanded`
```
sass: generateLoaders(['css?-autoprefixer', 'sass?indentedSyntax']),
scss: generateLoaders(['css?-autoprefixer', 'sass?outputStyle=expanded'])
```

**Comment by jhnns** [comment]
Less [does not remove `/* */` comments](http://less2css.org/#%7B%22less%22%3A%22a%20%7B%5Cn%20%20color%3A%20hotpink%3B%20%2F*%20test%20*%2F%5Cn%7D%22%7D). It's probably caused by the minification. Try to set `compress: false`.

If it doesn't work, please provide a minimal test repository that reproduces the error.
