### ISSUE TITLE
Less's `paths` option seem to be ignored when using less-loader

### ISSUE THREAD

**Issue by Justineo** [webpack-contrib/less-loader#168]
I can't get compilation work by configuring the `paths` option for `less-loader`. And thus Less's preprocessing plugins (which may modify `paths` after they are installed) cannot work using `less-loader`.

For example, [`less-plugin-est`](https://github.com/ecomfe/est) injects some mixin code before compiling `.less` files and it also [push its `src` directory into `paths` of the context](https://github.com/ecomfe/est/blob/dev/lib/injector.js#L38). But after `less-loader`'s `WebpackFileManager` taking over `@import` handling, Less stop searching `paths` for possible Less files.

**Comment by jhnns** [comment]
Thanks for reporting this.

I'm [currently refactoring that](https://github.com/webpack-contrib/less-loader/tree/feat/new-resolver). You will be able to disable the `WebpackFileManager` by providing a `paths` array.

It will be disabled because we won't support both ways. Either you let Less resolve the imports via `paths` or you configure your paths in your `webpack.config.js` and let the `WebpackFileManager`resolve it. Using both options does not make sense in my opinion.

Previous discussions:

https://github.com/webpack-contrib/less-loader/pull/75
https://github.com/webpack-contrib/sass-loader/pull/307

and probably more I don't remember now 😁
