### ISSUE TITLE
two kind of resolver? why?

### ISSUE THREAD

**Issue by yeganemehr** [webpack-contrib/less-loader#210]
Hi

I want to know why this loader have two kind of resolver and we should adjust our codes with loader and leave less compiler mechanism? while the others (like [ts-loader](https://github.com/TypeStrong/ts-loader)) have not.

I know `path` option and also read about [advanced mechanism to resolve files](https://webpack.js.org/configuration/resolve/).
I prepend a few lines of code to [loadFile](https://github.com/webpack-contrib/less-loader/blob/master/src/createWebpackLessPlugin.js#L35) method and all type of imports (with or without `~`) works fine.

```js
loadFile(filename, currentDirectory /* , options, environment */) { // eslint-disable-line class-methods-use-this
      if(filename.substr(0, 13) == 'node_modules/'){
            filename = '~'+filename.substr(13);
      }
      const url = filename.replace(matchMalformedModuleFilename, '$1');
      const moduleRequest = loaderUtils.urlToRequest(url, url.charAt(0) === '/' ? '' : null);
      // Less is giving us trailing slashes, but the context should have no trailing slash
      const context = currentDirectory.replace(trailingSlash, '');
      let resolvedFilename;
```
I sure you knew you can do this but why you didn't?

**Comment by jhnns** [comment]
There have been complaints that the webpack resolver is slower than the one provided by Less: https://github.com/webpack-contrib/less-loader/issues/54
[A recent performance test with the sass-loader](https://github.com/webpack-contrib/sass-loader/issues/296#issuecomment-288464857) indicates, that it's not the resolver which is slow, but the css-loader.

However, I decided to turn off the webpack resolver in case the `paths` option is set because this option makes no sense if you use the webpack resolver. This way, you can use Less the classical way or the webpack way.

I'm not sure if your example actually works. `filename` is a relative path that usually doesn't start with `node_modules/`. Maybe this example only works in your setup? Try to change that line in this repository and run the tests. The tests cover all the use-cases.

**Comment by yeganemehr** [comment]
Thanks @jhnns  for your reply.
I did your suggestion, forked less-loader and run tests with my changes.All passed.
Please checkout: [yeganemehr/less-loader](https://github.com/yeganemehr/less-loader)

and if It's okay to you I will create a PR.

**Comment by yeganemehr** [comment]
dear @jhnns did you check this out?

**Comment by michael-ciniawsky** [comment]
Feel free to open a PR for discussion about your suggested changes
