### ISSUE TITLE
Can we skip the `isLessCompatible` check and load all files through the webpack loader chain?

### ISSUE THREAD

**Issue by opatut** [webpack-contrib/less-loader#213]
I do *magic* stuff in custom loaders for all my `.less` files, some kinds of preprocessing. I would like them all to be loaded through those loaders with `loaderContext.loadModule` instead of `fs.readFile`, independent of their filename extension. Can I have a switch to configure that?

That regex (`const isLessCompatible = /\.(le|c)ss$/;`) is to me undocumented behaviour, so it'd be also nice to have that in the docs/readme.

Why was that chosen anyway? Can't we load .less/.css files through a raw loader by default also? I mean, the consumer would have to define a raw-loader with `issuer: /\.less/` when using `@import` I guess, but maybe we can find a way around this inconvenience? Or maybe not, adding two rules, one for js->less and one for less->less imports would make sense to me as a user, I'd be happy if it said so in the docs with a nice small explanation along the lines of 

> When importing .less files from javascript, the first rule is used. When you `@import` a less file from within less, the second rule matches. You can use this to configure preprocessing and postprocessing steps for both imports independently. Make sure your second rule exports valid LESS code, while the first exports your desired content for use in JavaScript.

**Comment by opatut** [comment]
Doesn't look too bad, IMO :)

```
// webpack.config.js
module.exports = {
    ...
    module: {
        rules: [
            // this rule matches for @import statements inside LESS code
            {
                test: /\.less$/,
                issuer: /\.less$/,
                use: [{
                    loader: "raw-loader" // loads the file as-is, no preprocessing
                }]
            },
            // this rule matches for all other .less imports
            {
                test: /\.less$/,
                use: [{
                    loader: "style-loader" // creates style nodes from JS strings
                }, {
                    loader: "css-loader" // translates CSS into CommonJS
                }, {
                    loader: "less-loader" // compiles Less to CSS
                }]
            }
        ]
    }
};
```

**Comment by unconfident** [comment]
Sounds remotely similar to #205. 

To summarize both issues under the same proposal I can put it this way: after path to the file(s) has been resolved less-loader should check if there's any loaders specified for that file either in webpack config or in import string itself and then either import file as is in case of plain import or let loaders do their magic.

I don't know if webpack exposes an API that would allow to perform this check easily from within a loader, but I definitely would love to see this feature implemented. It's worth exploring

**Comment by opatut** [comment]
Yeah, I thought about that too, but I didn't find such API in the webpack docs. It is probably possible to manually implement that, but that'd use private webpack internals :(

Also, I kind of like the idea of *having* to explicitly define how less loads `@import`ed .less files via webpack rules. Explicit over implicit, you know ;)

**Comment by unconfident** [comment]
> I kind of like the idea of _having_ to explicitly define how less loads `@import`ed .less files via webpack rules. Explicit over implicit, you know ;)

I would prefer if it would still fall back to current behavior if no rules are specified for the file. Being able to import any kind of text file is something that's naturally supported by the language and I expect that it would work without any loaders. 

Otherwise this rule

```js
{
    test: /\.less$/,
    issuer: /\.less$/,
    use: [{ loader: "raw-loader" }] // loads the file as-is, no preprocessing
},
```

would have to list dozen of extensions or contain a wildcard and massive `exclude` regexp next to it filtering out any files that can be covered by other rules just to match original behavior. Semantic UI's sources for example use custom extensions for their files - `.variables` and `.overrides` and your webpack configuration would have to be prepared for this.

Random thought: **Would be nice if webpack had something like a fallback loader. "Use this loader if no other matches"**

I would love to have control over how things are being imported, but I believe it should have sane default behavior or it's just going to be pain to use and most people are gonna avoid it
