### ISSUE TITLE
Parse error: syntax error, unexpected 

### ISSUE THREAD

**Issue by PatrycjaNYC** [webpack-contrib/less-loader#281]
The font awesome doesn't let me to be activated. I get error: Parse error: syntax error, unexpected.... wp-content/plugins/font-awesome/includes/class-fontawesome.php on line 116
And line 116 says: const REST_API_NAMESPACE = self::PLUGIN_NAME . '/v' . self::REST_API_VERSION;

I didn't touch the code of the plugin. How can I fix it,please? I am not developer, only know basics, so please be patient with me. Thanks. 

* Operating System:MAcOS Sierra
* Node Version:
* NPM Version:
* webpack Version:
* less-loader Version:

This issue is for a:

- [ ] **bug**
- [ ] **feature** request
- [ ] **modification** request

##### CLI Command

```bash
  # paste the CLI command you're using. if this isn't applicable, it's safe to remove.
  $ {the command}
```

##### webpack.config.js

```js
  // If your bitchin' code blocks are over 20 lines, please paste a link to a gist
  // (https://gist.github.com).
```

```js
  // additional code, HEY YO remove this block if you don't need it
```

**Comment by kirkschnable** [comment]
For your information, I ran into the same issue with the Font Awesome WordPress plugin, and while searching for any information I came across this bug report.  I resolved this issue by updating PHP on my server to version 7.3.  It appears this may be due to some code in the plugin that is incompatible with some older PHP 5.x versions.  If you are running one of these versions, your server should be updated anyways since they are EOL.

**Comment by evilebottnawi** [comment]
Information is not enough for debugging, sorry

**Comment by larsonreever** [comment]
I think here you can get more detailed info on [Parse Error: Syntax Error Unexpected](https://secure.wphackedhelp.com/blog/fix-parse-error-syntax-error-unexpected-wordpress/#Tools_To_Help_You_Fix_The_Syntax_Error_in_WordPress). it explains in detail about its causes and tools which can come handy in resolving it further.
