### ISSUE TITLE
resolve.alias support

### ISSUE THREAD

**Issue by kentcdodds** [webpack-contrib/less-loader#32]
I'm trying to create a custom loader that would add an import for a file that has something I want all files to have (variables and mixins for example). I want this to be possible:

``` js
{
  resolve: {
    alias: {
      azGlobalLess: __dirname + '/app/global.less'
    }
  }
}
```

then I have a custom loader (`global-less-imports-loader`) that does:

``` js
module.exports = function(source) {
  return '@import "azGlobalLess";\n' + source;
};
```

then in my less

``` less
@import 'azGlobalLess';
```

This currently fails with:

> ERROR in ../~/css-loader!../~/less-loader!../build/global-less-imports-loader.js!./components/states/login/index.less
> Module build failed: Cannot resolve 'file' or 'directory' ./azGlobalLess.less in /Users/kentcdodds/Developer/alianza/atac5/app/components/states/login
>  @ /Users/kentcdodds/Developer/alianza/atac5/app/components/states/login/index.less (line 1, column 0)
>  near lines:
> 
>    @import "azGlobalLess";
>    .location(LoginCtrl, {
>  @ ./components/states/login/index.less 4:14-336

Obviously, I believe the custom loader bit is irrelevant. What I really need to get working is the resolve.alias working for less-loader. Am I doing something wrong?

**Comment by stefanfisk** [comment]
I'd love to get this solved as well, and any tips on where to start would be greatly appreciated.

**Comment by jhnns** [comment]
Does it work with `@import '~azGlobalLess';`?

**Comment by kentcdodds** [comment]
Actually yes it does. Sorry, I should have mentioned that and closed this issue. Thanks!

**Comment by mkralla11** [comment]
I know this issue is closed, but I recently came across a similar error message given the same criteria, here is my package.json for reference so you don't have to guess what versions I'm using:
```
...
  "devDependencies": {
    "ansi-to-html-umd": "^0.4.2",
    "babel-core": "^6.6.0",
    "babel-loader": "^6.2.4",
    "babel-polyfill": "^6.6.1",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-react": "^6.5.0",
    "babel-preset-react-hmre": "^1.1.0",
    "babel-preset-stage-0": "^6.5.0",
    "copy-webpack-plugin": "^1.1.1",
    "cors": "^2.7.1",
    "css-loader": "^0.23.1",
    "express": "^4.13.4",
    "extract-text-webpack-plugin": "^1.0.1",
    "file-loader": "^0.8.5",
    "gulp": "^3.9.1",
    "gulp-run": "^1.6.12",
    "gulp-util": "^3.0.7",
    "less": "^2.6.1",
    "less-loader": "^2.2.2",
    "path": "^0.12.7",
    "postcss-loader": "^0.8.1",
    "resolve-url-loader": "^1.4.3",
    "run-sequence": "^1.1.5",
    "style-loader": "^0.13.0",
    "url-loader": "^0.5.7",
    "webpack": "^1.12.14",
    "webpack-dev-middleware": "^1.5.1",
    "webpack-hot-middleware": "^2.8.0"
  }
...
```

Here is the custom_styles.less file trying to import the webpack.config aliased lesshat.less file:
```
@import "~lesshat";
```

here is part of my webpack.config that matters to this issue:
```
...
const PATHS = {  
  appAssets: Path.join(__dirname, 'app/assets'),  // Phoenix's default asset path
  publicAssets: Path.join(__dirname, 'public/assets') // Build path
}
...

module.exports = {
...
  resolve: {
    extensions: ['', '.js', '.css'],
    root: PATHS.appAssets,
    alias: {
      "lesshat.less": PATHS.appAssets + '/stylesheets/lesshat.less'
    }
  }
...
}
```

**Note that I have to specifically put the 'less' extension on my alias to make the lesshat.less alias work**. My initial thought (without looking at the less-loader and less compiler code in detail) was that because my error message from webpack was stating 'Cannot resolve 'file' or 'directory' lesshat.less', I made an assumption that less/less-loader was was automatically tagging on a `.less` extension to the import before trying to load it, without me knowing. Clearly, my `resolve.alias` originally coded to be just `lesshat`, thinking it would function like my other js aliases. So, I tagged on `.less` to the alias name, to trick webpack/less-loader/less into looking up my alias that now correctly matched what the error message was trying to import, aka `lesshat.less`. And it worked!

**Comment by jhnns** [comment]
Interesting. Maybe less is appending it automatically. Admittedly, this makes it hard to configure `resolve.alias` correctly. Needs further research.

**Comment by al3x-huang** [comment]
Still having this issue. Has there been any progress on this?

**Comment by jhnns** [comment]
@mkralla11 will be fixed with less-loader 4.x

**Comment by mkralla11** [comment]
I appreciate you working on this! I will take a look today. Thanks again!
