### ISSUE TITLE
Error evaluating function `round`: argument must be a number

### ISSUE THREAD

**Issue by iamsjh** [webpack-contrib/less-loader#404]
@input-padding-vertical-base: max(
  round((@input-height-base - @font-size-base * @line-height-base) / 2 * 10) / 10 -
^
Error evaluating function `round`: argument must be a number

**Comment by alexander-akait** [comment]
Thank you for creating this issue. However, issues need to follow one of our templates so that we can clearly understand your particular circumstances.

Please help us help you by recreating the issue using one of our templates.

This problem from `less`, we just wrapper for running `less`, you need to fix the problem in your code

**Comment by xoxefdp** [comment]
Im having same issue reported here, in my case for less-loader -> "10.0.1"
I was using less-loader -> "7.1.0" it does not happenand this not happen,, just with the later version

**Comment by francoisp-houzz** [comment]
From less 4.0.0  and parenthesis are now required around divisions, unless configured otherwise.

See https://github.com/less/less.js/releases/tag/v4.0.0
> Parens-division now the default math setting

less-loader 7.2.0 and above depend on less 4.x.x and should exhibit the same behavior.
