### ISSUE TITLE
@import inserts duplicates

### ISSUE THREAD

**Issue by hunterloftis** [webpack-contrib/less-loader#7]
If you have file foo:

``` less
@import 'base.less';

.foo { ... }
```

and file bar:

``` less
@import 'base.less';

.bar { ... }
```

...and you webpack both `foo` and `bar` into the same `bundle.js`, the bundle will have two instances of all rules from `base.less`. (this is true even if using the dedupe plugin).

**Comment by sokra** [comment]
The solution is to use `@import (reference)`:

``` css
@import (reference) 'base.less';

.foo { ... }
```

**Comment by schickling** [comment]
Do I have to import it somewhere without reference or does it guarantee to import it once if using just `@import (reference)`?

**Comment by jhnns** [comment]
If the imported file contains classes that you are using in your HTML, you should still import it somewhere without `(reference)`.

Importing something with `@import (reference)` means that you are not interested in the css output, but in variables, mixins or css-classes because you are extending them.

**Comment by schickling** [comment]
Thanks @jhnns for this excellent explanation!

**Comment by loktar00** [comment]
I think reference is an alright solution for some cases, however I've ran into a situation where this doesn't quite work. Here is how we currently layout our projects components

![Layout](http://i.imgur.com/CZBQR0L.png)

Each component has a less file associated with it, within those files we `(reference)` our primary file which imports variables, bootstrap, ect. However since we have quite a few components that use `react-bootstrap` and reference col/row/ect. we end up with some rules duplicated for every single component like the following

![Duplicate styles](http://i.imgur.com/xWDsNIn.png)

heh those styles are repeated 30 or so times, and as you can see by the line numbers our generated style sheet is HUGE. In some cases this causes issues when we have a custom style in a component, since it may end up in the middle of those dupes its overridden. I've fixed it on our end mostly by using a css minifier during our release build that removes the duplicates.

Going forward in my case on any new project it just seems better to have a few `less` files rather than one per component. I'm not sure what the correct solution would be in this case, finding duplicates and not re-adding would be ideal but I imagine would be a lot of work, however I just wanted to at least post this for others who may run into a similar issue.

**Comment by QuentinRoy** [comment]
Any progress on this point ? IMO it is a big issue.

**Comment by gunar** [comment]
It'd be cool for less-loader to de-duplicate by itself.

**Comment by gregvenech** [comment]
+1

**Comment by davidpelayo** [comment]
+1 Big issue I think. Many times the same styles applied leading to performance issues...!

**Comment by thkdog** [comment]
The `@import (reference)` way works great form me.
Especially using with vue-router, there is a common App.vue for entrance, where I put the `@import` common.less for once, and the rest pages, just import them with (reference).

**Comment by loktar00** [comment]
How I resolved this last year was just to do the opposite.

I have a primary less file, and just import anything new into it (using reference still). Everything is added once and it works great. Only downside is having to update the main file with the new reference, but it's a small amt of work for a huge improvement.

**Comment by geraldlrh** [comment]
+1 Has any plan to fix it? @sokra

**Comment by jhnns** [comment]
I don't think that we will fix this. It's less' behavior and webpack's output should not be different than less' output.

**Comment by phun-ky** [comment]
While the original issue here is related to sass/less/stylus, a fix/hack/patch for this is to use the `optimize-css-assets-webpack-plugin` in conjunction with `extract-text-webpack-plugin` to produce, like this: https://gist.github.com/phun-ky/766e5ec9f75eac61c945273a951f0c0b. 

If you want to use this in dev, you will have to use a plugin like `write-file-webpack-plugin` to force webpack to write the file to disk in dev.

**Comment by tommck** [comment]
I don't see this as "less' behavior" at all.
The default behavior for @import in less is "@import (once)".
So, in my opinion, this is the **opposite** of less' behavior.

**Comment by jabadia** [comment]
I agree with @tommck 

`
// base.less
@front-color: red;
@back-color: blue;

.base {
	color: @front-color;
}


// a.less
@import 'base';

.a {
	color: @front-color;
}

// b.less
@import 'base';

.b {
	background: @back-color;
}

// final.less
@import 'a';
@import 'b';


// $ lessc final.less > final.css

// final.css
.base {
  color: red;
}
.a {
  color: red;
}
.b {
  background: blue;
}
`

**Comment by Grohden** [comment]
I **think** solved this problem for my gulp builds ( https://github.com/Grohden/angularjs-gulp-build/blob/04048072aa7fc0566a8e20dda0ba27f57bbe7892/src/builders/tasks/LessStyles.js#L19, which basically uses a 'all-imports.less' vinyl file).

This is not possible in webpack? to accumulate all paths into one virtual less importing all files and only then apply less compiler?

**Comment by jhnns** [comment]
> The default behavior for @import in less is "@import (once)".

If less' default behavior now is `@import (once)` and the issue still exists, we should revise it. At the time of writing, it was not less' default behavior.

**Comment by diby3ndu** [comment]
I completely agree with @tommck . Even if we explicitly write **@import (once) 'some-module'** **multiple times** in the same file, it's creating duplication. 
Any plan to fix this ?

**Comment by jhnns** [comment]
Not yet. PRs welcome though :)

**Comment by jonleung** [comment]
👍

**Comment by sbruinsje** [comment]
Yes less supports loading less files only once, but the loader doesn't seem to respect the `(once)` when importing.

**Comment by lz777** [comment]
> The solution is to use `@import (reference)`:
> 
> ```css
> @import (reference) 'base.less';
> 
> .foo { ... }
> ```

awsome!

**Comment by evilebottnawi** [comment]
Answer here https://github.com/webpack-contrib/less-loader/issues/7#issuecomment-69487144, less works as expected, you can use css optimizer to reduce duplicates

**Comment by tommck** [comment]
Lame

**Comment by Jojo-wwi** [comment]
> This is indeed a problem. Less works this way. Luckly gzip can reduce the duplication...
> 
> Do you have a proposal how to fix this?
> 
> Here is a more complex example:
> 
> ```css-less
> $XYZ = "foo";
> @import 'base.less';
> ```
> 
>  ```css-less
> $XYZ = "bar";
> @import 'base.less';
> ```
