### ISSUE TITLE
Loader can't find less file from the node_modules root

### ISSUE THREAD

**Issue by AlexKovalevych** [webpack-contrib/less-loader#77]
Trying to build semanti-ui-less with webpack. For some reason such import:

```
@import "~/semanti-ui-less/theme.less"
```

doesn't work:

ERROR in ./~/css-loader!./~/less-loader!./frontend/semantic/theme.less
Module build failed: Cannot resolve 'file' or 'directory' /semantic-ui-less/theme.less in 
..
 near lines:

   @import "~/semantic-ui-less/theme";

Did i misunderstood usage of `~` here? File is located in `node_modules/semanti-ui-less/theme.less"`

**Comment by cordoval** [comment]
:+1: same problem please help

**Comment by grofit** [comment]
:+1: 

I have this same issue where it doesnt seem to resolve as it should for a custom module, I have even tried manually setting moduleDirectories config and extensions to include less files etc.

**Comment by cordoval** [comment]
we are going another route

**Comment by grofit** [comment]
Can you elaborate more? currently to just get things moving I am manually resolving to the node_modules folder but I would rather not do this if there is a workaround.

**Comment by cordoval** [comment]
basically we moved to react and are rewriting the frontend so we don't use semantic in this way but rather via a semantify or other libraries with webpack

**Comment by oller** [comment]
Is this not just the case that you should be using

```@import "~semanti-ui-less/theme.less"```

instead of

```@import "~/semanti-ui-less/theme.less"```

You just want the path to start `"~nodePackage` not `"~/nodePackage"`

**Comment by grofit** [comment]
Sorry was on another project, returned to this and that doesnt work, I get the following errors:

```
Potentially unhandled rejection [2] '~some-module-name/less/icons.less' wasn't found. Tried - C:\some-dir\src\less\~some-module-name\less\icons.less,~some-module-name\less\icons.less in file C:\some-dir
\src\less\lookups.less line no. 1
```

The actual line in `lookup.less` looks like:

```less
@import "~some-module-name/less/icons.less";
```

So it is not resolving the node modules directory.

**Comment by grofit** [comment]
Ignore my comments, it appears that it was not using the less-loader module correctly so now this has been fixed our side.

**Comment by rovolution** [comment]
@grofit out of curiosity, how did you resolve this issue? I am running into a similar problem

**Comment by grofit** [comment]
We resolved the issue by actually using less-loader.... it made me chuckle as we have a few build outputs from our gulp script and it seemed that webpack was the issue here and the less being generated was throwing the error. However after digging through the build script logic instead of the less and config, I realised the actual erroring part was just a gulp-less generator not a webpack based generator. So after moving the logic to use webpack and less-loader it didnt error and seemed to resolve the files correctly.

I am running windows as well as a few people here thought maybe it was an OS related issue but I don't think it is. I am using latest version of `less-loader` with the current npm latest version of `webpack-stream`.
