### ISSUE TITLE
Support less-plugin-npm-import style

### ISSUE THREAD

**Issue by sparty02** [webpack-contrib/less-loader#94]
In attempting to import some less that was developed by another team, I hit a bump because they were using an import syntax like `@import "npm://packagename/path/to/file.less";` which apparently is prescribed by the [less-plugin-npm-import](https://github.com/less/less-plugin-npm-import) maintained by the less team.

Should the less-loader support this syntax?

**Comment by liujingbreak** [comment]
I found that even in Webpack2 config file with less-loader@4.0.2,
```json
{loader: '@dr/less-loader', options: {
	sourceMap: false,
	plugins: [new NpmImportPlugin()]
}},
```
"npm://" still does not work. `plugins` option is buggy.

**Comment by jhnns** [comment]
> Should the less-loader support this syntax?

Since there is a plugin, I don't think that the less-loader should support this out of the box. If the plugin option doesn't work, we need to find out why.

@liujingbreak could you setup a small example repo to make this reproducible? We have [a test for plugins](https://github.com/webpack-contrib/less-loader/blob/a48295810fface3c98bcf49b01dbc85d7a38cef1/test/index.test.js#L184-L197), so I would like to know why it's still not working.

**Comment by michael-ciniawsky** [comment]
https://github.com/webpack-contrib/less-loader/issues/200#issuecomment-338870688
